In [1]:
a = [1.0, 2.0, 3.0]

In [2]:
a[0]

1.0

In [3]:
a[2]

3.0

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0],[2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points[0,1]

tensor(1.)

In [15]:
points[1]

tensor([5., 3.])

In [16]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [17]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [18]:
points[1:,0]

tensor([5., 2.])

In [19]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])