In [1]:
import numpy as np

In [3]:
data1 = [5, 7, 9, 20]
arr1 = np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [4]:
data2 = (5, 7, 9, 20)
arr2 = np.array(data2)
arr2

array([ 5,  7,  9, 20])

In [5]:
data3 = [[1, 2, 3, 4,], [5, 6, 7, 8]]
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr3.shape

(2, 4)

In [7]:
arr3.dtype

dtype('int64')

In [12]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.empty(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.empty((2,2))

array([[-2.68156159e+154, -2.00389689e+000],
       [ 2.37663529e-312,  2.78134232e-309]])

In [16]:
np.empty((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
for i in np.arange(8):
    print(i)

0
1
2
3
4
5
6
7


In [19]:
[i for i in np.arange(8)]

[0, 1, 2, 3, 4, 5, 6, 7]

In [20]:
{i:k for k, i in enumerate(np.arange(8))}

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7}

In [21]:
arr4 = np.ones_like(arr3)
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
arr5 = np.zeros_like(arr4)
arr5

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
arr5.dtype

dtype('int64')

In [24]:
data = [[2, 4, 5], [3, 5, 7]]
arr = np.array(data)
arr

array([[2, 4, 5],
       [3, 5, 7]])

In [26]:
arr.ndim #数据轴的个数,秩

2

In [27]:
arr.shape #维度

(2, 3)

In [28]:
arr.size #元素个数

6

In [29]:
arr.itemsize #数组中每个元素的字节大小

8

In [30]:
arr.dtype #数据类型

dtype('int64')

In [31]:
arr2 = np.arange(5, dtype='float64')
arr2

array([0., 1., 2., 3., 4.])

In [32]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [33]:
arr1.dtype

dtype('int64')

In [34]:
arr2 = arr1.astype(np.float64)
arr2

array([0., 1., 2., 3., 4., 5.])

In [35]:
arr2.dtype

dtype('float64')

In [36]:
arr3 = arr1.astype('string_')
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

In [37]:
arr3.dtype

dtype('S21')

In [38]:
arr = np.array([2.3, 7.5, 5.6, 9.8])
arr

array([2.3, 7.5, 5.6, 9.8])

In [39]:
arr.astype('int64')

array([2, 7, 5, 9])

In [40]:
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

In [41]:
arr3.astype(np.int64)

array([0, 1, 2, 3, 4, 5])

In [42]:
arr1 = np.arange(10)
arr.dtype

dtype('float64')

In [43]:
arr2 = np.ones(5)
arr2.dtype

dtype('float64')

In [44]:
arr3 = arr1.astype(arr2.dtype)
arr3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr.reshape((9,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [48]:
arr.reshape((1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [49]:
arr.reshape((6,7))

ValueError: cannot reshape array of size 9 into shape (6,7)

In [50]:
arr.reshape((3,-1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr.reshape((-1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [55]:
arr.reshape((3,-1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr2 = arr.reshape((3,-1))

In [58]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
arr2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
arr3 = np.arange(9,18).reshape(3,-1)
arr3

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [82]:
np.concatenate([arr2,arr3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [83]:
np.concatenate([arr2, arr3], axis=1)

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [87]:
arr4 = np.vstack((arr2, arr3))
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [88]:
arr5 = np.hstack((arr2, arr3))
arr5

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [90]:
np.split(arr4,[9,2])

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [101]:
np.vsplit(arr4, 6)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]]),
 array([[15, 16, 17]])]

In [104]:
np.hsplit(arr4, 3)

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [105]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [109]:
arr4.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [110]:
arr = np.random.randint(100, 200, size=(5,4))

In [111]:
arr

array([[194, 144, 182, 120],
       [102, 166, 164, 192],
       [164, 163, 197, 155],
       [187, 192, 151, 120],
       [199, 174, 190, 127]])

In [112]:
arr = np.random.randn(2, 3, 5)

In [113]:
arr

array([[[ 0.10647448,  0.8683132 ,  0.36207672,  0.66342718,
         -0.33220032],
        [-1.10587958, -3.10163856,  0.29673772, -0.10972036,
          1.3001411 ],
        [-1.47636562, -0.59587421, -0.37770021, -0.84822111,
          0.1953895 ]],

       [[-1.12875575, -0.80896808,  1.06596737, -0.38138352,
         -1.79544642],
        [-0.30419824,  0.14071556,  1.17336448,  1.51449042,
         -1.06712342],
        [-0.06277782, -0.88731533, -1.30976877, -0.40636206,
          0.89625019]]])

In [115]:
arr = np.random.normal(4, 5, size=(3,5)) #指定均值和标准差的随机数
arr

array([[ 7.60888453,  1.52240974,  2.37946063,  7.37379272, 10.31187716],
       [14.09480556,  9.03631847,  2.29821262,  3.16511629,  5.8708284 ],
       [14.0179529 ,  3.48497113,  5.80648827,  5.19418371,  2.22006669]])

In [116]:
arr = np.random.randint(100, 200 ,(5,4))
arr

array([[109, 168, 148, 157],
       [195, 111, 117, 119],
       [192, 103, 109, 175],
       [167, 171, 101, 161],
       [182, 194, 164, 136]])

In [117]:
np.random.permutation(arr)

array([[109, 168, 148, 157],
       [195, 111, 117, 119],
       [182, 194, 164, 136],
       [192, 103, 109, 175],
       [167, 171, 101, 161]])

In [118]:
arr

array([[109, 168, 148, 157],
       [195, 111, 117, 119],
       [192, 103, 109, 175],
       [167, 171, 101, 161],
       [182, 194, 164, 136]])

In [119]:
np.random.shuffle(arr)

In [120]:
arr

array([[192, 103, 109, 175],
       [109, 168, 148, 157],
       [167, 171, 101, 161],
       [195, 111, 117, 119],
       [182, 194, 164, 136]])

# 数组的索引和切片

## 数组的索引

In [121]:
import numpy as np

> 一维略

In [128]:
arr = np.arange(15).reshape(3,5)

In [129]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
arr[0]

array([0, 1, 2, 3, 4])

In [131]:
arr[0][0]

0

In [132]:
arr[0,0]

0

In [133]:
arr = np.arange(12).reshape(3,4,1)

In [134]:
arr

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [136]:
arr2 = np.arange(12).reshape(3,2,2)
arr2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [137]:
arr[0]

array([[0],
       [1],
       [2],
       [3]])

In [139]:
arr[0][0][0]

0

In [140]:
arr[:2]

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

In [148]:
arr[:2][1:][0][:2][0][0]

4

In [155]:
arr[:2,1:,0,]

array([[1, 2, 3],
       [5, 6, 7]])

In [156]:
arr[:2,1:,0,0]

IndexError: too many indices for array

In [162]:
datas = np.random.randint(-1, 3, size=(7,5))
datas

array([[ 1, -1, -1,  2,  2],
       [ 1,  2, -1, -1, -1],
       [ 0,  0, -1, -1,  1],
       [ 0,  2,  1,  0, -1],
       [ 2,  2,  1,  2, -1],
       [ 1, -1,  0,  1,  0],
       [ 0,  1,  1,  0, -1]])

In [163]:
datas[datas==0] = 1

In [164]:
datas

array([[ 1, -1, -1,  2,  2],
       [ 1,  2, -1, -1, -1],
       [ 1,  1, -1, -1,  1],
       [ 1,  2,  1,  1, -1],
       [ 2,  2,  1,  2, -1],
       [ 1, -1,  1,  1,  1],
       [ 1,  1,  1,  1, -1]])

# 数组运算

In [166]:
a = [1,2,3]
b = [x*10 for x in a]
b

[10, 20, 30]

In [167]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [171]:
arr != 100000

array([ True,  True,  True])

In [173]:
np.abs(arr)

array([1, 2, 3])

In [174]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [175]:
np.square(arr)

array([1, 4, 9])

In [178]:
arr = np.random.normal(3,4,size=(9,89))
arr

array([[-5.61236941e-01,  3.39565541e+00,  1.10779157e+00,
         8.18373741e+00,  1.13310458e+01,  1.13535542e+01,
         1.87502945e+00,  4.18492929e+00,  2.91401307e-02,
         3.56587439e+00,  5.64309465e+00, -5.52209596e+00,
         5.34688869e+00,  2.09774688e+00,  1.01571411e+01,
         3.63475347e-01,  1.30709320e+01,  4.48031753e+00,
        -7.30163515e-01,  6.10545233e+00,  1.46374607e+00,
         3.92317416e+00,  4.79440876e+00,  4.18705507e+00,
         3.01144804e-01,  2.80038652e+00,  4.87042885e+00,
         2.68287074e+00,  7.17242938e+00,  5.66102983e+00,
         1.87317973e+00,  5.78877308e+00,  1.35754535e+01,
         3.12282511e+00,  9.15689382e-01,  3.50473333e+00,
         1.95641324e+00,  4.97653567e+00,  6.18792743e+00,
         4.60273605e+00, -9.54288791e-01,  2.66973079e+00,
         2.58301810e+00,  5.40194309e+00,  8.19386232e+00,
        -1.10775381e+00,  1.17176966e+01, -2.36078923e+00,
         7.34258314e-02,  7.69605286e-01,  5.19249334e+0

In [179]:
np.modf(arr)

(array([[-5.61236941e-01,  3.95655409e-01,  1.07791569e-01,
          1.83737413e-01,  3.31045797e-01,  3.53554172e-01,
          8.75029454e-01,  1.84929287e-01,  2.91401307e-02,
          5.65874387e-01,  6.43094650e-01, -5.22095963e-01,
          3.46888689e-01,  9.77468776e-02,  1.57141091e-01,
          3.63475347e-01,  7.09320233e-02,  4.80317535e-01,
         -7.30163515e-01,  1.05452331e-01,  4.63746069e-01,
          9.23174157e-01,  7.94408758e-01,  1.87055068e-01,
          3.01144804e-01,  8.00386522e-01,  8.70428849e-01,
          6.82870739e-01,  1.72429381e-01,  6.61029833e-01,
          8.73179734e-01,  7.88773079e-01,  5.75453528e-01,
          1.22825114e-01,  9.15689382e-01,  5.04733327e-01,
          9.56413239e-01,  9.76535665e-01,  1.87927427e-01,
          6.02736050e-01, -9.54288791e-01,  6.69730790e-01,
          5.83018102e-01,  4.01943091e-01,  1.93862321e-01,
         -1.07753811e-01,  7.17696576e-01, -3.60789229e-01,
          7.34258314e-02,  7.69605286e-0

In [180]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.array([True, False, False, True])

In [181]:
result = np.where(arr3, arr1, arr2)

In [182]:
result

array([1, 6, 7, 4])

In [183]:
arr = np.random.randn(4,4)
arr

array([[ 1.33414141, -0.40011312, -0.41062148, -0.15768015],
       [-0.82061156, -0.65279401,  0.48769189, -0.89187311],
       [ 0.00810894, -1.45415802,  0.9723724 ,  1.14816049],
       [ 0.23720891, -1.4760781 ,  0.7771395 ,  0.02476203]])

In [184]:
new_arr = np.where(arr>0, 1, -1)

In [185]:
new_arr

array([[ 1, -1, -1, -1],
       [-1, -1,  1, -1],
       [ 1, -1,  1,  1],
       [ 1, -1,  1,  1]])

In [186]:
arr.sum()

-1.2743439814995217

In [187]:
arr.mean()

-0.0796464988437201

In [189]:
arr.std()

0.8434630865001602

In [192]:
arr.var()

0.7114299782883768

In [193]:
arr.mean(1)

array([ 0.09143166, -0.4693967 ,  0.16862095, -0.10924192])

In [196]:
arr.mean(axis=1)

array([ 0.09143166, -0.4693967 ,  0.16862095, -0.10924192])

In [197]:
arr.argmax(0)

array([0, 0, 2, 2])

In [198]:
arr.argmax(1)

array([0, 2, 3, 2])

In [199]:
arr.any()

True

In [200]:
arr.all()

True

In [201]:
arr.sort()

In [202]:
arr

array([[-0.41062148, -0.40011312, -0.15768015,  1.33414141],
       [-0.89187311, -0.82061156, -0.65279401,  0.48769189],
       [-1.45415802,  0.00810894,  0.9723724 ,  1.14816049],
       [-1.4760781 ,  0.02476203,  0.23720891,  0.7771395 ]])

In [203]:
arr.sort(1)

In [204]:
arr

array([[-0.41062148, -0.40011312, -0.15768015,  1.33414141],
       [-0.89187311, -0.82061156, -0.65279401,  0.48769189],
       [-1.45415802,  0.00810894,  0.9723724 ,  1.14816049],
       [-1.4760781 ,  0.02476203,  0.23720891,  0.7771395 ]])

In [205]:
np.unique(arr)

array([-1.4760781 , -1.45415802, -0.89187311, -0.82061156, -0.65279401,
       -0.41062148, -0.40011312, -0.15768015,  0.00810894,  0.02476203,
        0.23720891,  0.48769189,  0.7771395 ,  0.9723724 ,  1.14816049,
        1.33414141])

# 图像处理

In [209]:
from PIL import Image

In [208]:
!pip3 install Pillow

     |████████████████████████████████| 3.9 MB 671 kB/s eta 0:00:01


In [210]:
im = np.array(Image.open('/Users/meininghang/test.png'))
im.shape

(620, 762, 4)

In [211]:
im.dtype

dtype('uint8')

In [212]:
im

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

In [214]:
b = [255, 255, 255, 255] - im

In [217]:
new_im = Image.fromarray(b.astype('uint8'))
new_im.save('/Users/meininghang/test2.png')