# 4机器学习中的数学

## 4.1 向量

### 4.1.2表示向量

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
a = np.array([2, 1])

In [3]:
a

array([2, 1])

In [4]:
type(a)

numpy.ndarray

### 4.1.3列向量

In [5]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [6]:
d = np.array([[1],[2]])
d

array([[1],
       [2]])

### 4.1.4转置T

In [7]:
a.T

array([2, 1])

In [8]:
a

array([2, 1])

一维ndarrar转置后还是自己

In [9]:
c.T

array([[1, 3],
       [2, 4]])

In [10]:
c

array([[1, 2],
       [3, 4]])

In [11]:
d.T

array([[1, 2]])

In [12]:
d

array([[1],
       [2]])

In [13]:
d.T.T

array([[1],
       [2]])

### 4.1.7内积

In [14]:
b = np.array([2,1])
c = np.array([3,4])
b.dot(c)

10

### 4.1.8向量的模

向量的模本质上是向量的长度

In [15]:
b

array([2, 1])

In [16]:
np.linalg.norm(b)

2.23606797749979

### 4.2.2 通过内积求和

In [18]:
a = np.ones(1000)
b = np.arange(1,1001)
a.dot(b)

500500.0

## 4.3累乘

In [ ]:
从